version: '3.7'
services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    environment:
        XDEBUG_CONFIG: remote_host=192.168.1.11