FROM php:8.0.13-fpm-alpine3.13
COPY ./php.ini /usr/local/etc/php/php.ini
COPY ./ash-scripts/ /etc/profile.d/
WORKDIR /var/www

ENV ENV="/etc/profile"

# Custom docker group for perm issues
RUN addgroup --gid 1077 dockergroup
RUN addgroup root dockergroup
RUN addgroup www-data dockergroup

# Install server software
RUN apk update
RUN apk add nano zip unzip zlib-dev libpng-dev libjpeg-turbo-dev

# Install required php extensions
RUN docker-php-ext-configure gd --with-jpeg
RUN docker-php-ext-install bcmath gd

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer